language: bash

sudo: 'required'

notifications:
  email:
    on_success: always
    on_failure: always
  slack:
    rooms:
      secure: STa7nir1Y2Ku9ZNgnnaEsQizfv87PMqa457UhD6kOLnvUU79AXBGHV94qW0x0Hqd39kKXbJQVlgyBOQ6R24NjSAcLFwMZo/c7LrrO46zCFYtxw0uEP3nIIpuPsnUYiAXaefHfmNCbIgLYSJncCiwO1+Zd/RFw5JRtg8hhRetGn67898rLxVYR4eyjSuoxmag65uFXlFNAX/RlR2vqKTNuktB8noiebSn58Qb4t/5jy/XL1h1PV5XC0GkjEg4N7sW6+v6kNnpVOWP93fITOV7ukVFNoBndxYXj1mswrrGTLwm1eNdXC95SWUxqKpcq6sptbJvHZlbN9dLh0OKaLoNntaepLQUA9KUTP34Wnr9JvifTb8aBL1Kr1r7PwV8Y3BHMm0HFDaj1BjfQjENfPsR2/aviwirV7xSdBc1xukf8ZqfI/vX88vEHe/8Qh6hT3juqlGHk564sgO5ftGpE879+PHgEjHxSsb7WfixKg/z1tfCW78b08nrAqe41lWoWUv+cLQpKqkNhJ3wLrJc7SE2NEwEKnRe1Az68oS+sxUeOUwEt1IZjM5ROVD8yZM6oAlmjkWOt0svN57VK3WFnCsGvvt35nY6zOh4kAIaTgEdqa6vue+RAcBU3eE3ZU0ytSNnKNMGwCvD6cfG5NK1oiQRIu+PjnMdKpje4pK7AJqT/Yw=
    on_success: always
    on_failure: always

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.0

before_install:
  - chmod +x ./.travis/main.sh
  - ./.travis/main.sh

install:
  - git clone https://github.com/litespeedtech/ols-docker-env.git
  - docker-compose build --no-cache
  - docker-compose up -d

before_script:
  - docker image ls
  - sleep 15

script:  
  - curl -Ik http://localhost:80/
  - curl -Ik http://localhost:443/

after_success:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker-compose push litespeed/openlitespeed-beta

after_script:
  - docker-compose stop
  - docker-compose rm -f





