language: bash

sudo: 'required'

notifications:
  email:
    if: branch = master
    recipients:
      - eleu@litespeedtech.com
      - larsh2690@hotmail.com
    on_success: always
    on_failure: always

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.0

before_install:
  - chmod +x ./.travis/main.sh
  - ./.travis/main.sh

install:
  - git clone https://github.com/litespeedtech/ols-docker-env.git
  - docker-compose build --no-cache
  - docker-compose up -d

before_script:
  - docker image ls
  - sleep 15

script:  
  - curl -Ik http://localhost:80/
  - curl -Ik http://localhost:443/

after_success:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker-compose push litespeed/openlitespeed-beta

after_script:
  - docker-compose stop
  - docker-compose rm -f





